name: Pull Request

on:
    pull_request:

jobs:
    incremental-deploy:
        name: Run Incremental Deploy Workflow
        uses: ./.github/workflows/incremental-deploy.yml
        secrets: inherit
        with:
            baseRef: 'origin/${GITHUB_BASE_REF}'
            targetRef: 'HEAD'
            validateOnly: true
